# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backsys', '0002_auto_20170206_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_type',
            name='amount',
            field=models.CommaSeparatedIntegerField(max_length=10),
        ),
    ]
