# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 06:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.TextField(default=b'', null=True)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(default=b'0', max_length=100)),
                ('tickets_no', models.IntegerField()),
                ('supervisor', models.ForeignKey(default=b'0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('pin', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('seller', models.CharField(max_length=20, null=True)),
                ('Name', models.CharField(max_length=100)),
                ('ticket_type', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 10, 28, 6, 0, 30, 787000, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='tickettype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tike_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickapp.Show')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='event',
            field=models.ForeignKey(default=b'0', on_delete=django.db.models.deletion.CASCADE, to='tickapp.Show'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
