# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 8, 58, 50, 838000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
