# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0002_auto_20170429_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickapp.profile'),
        ),
    ]
