# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0002_auto_20170220_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Description',
            field=models.TextField(),
        ),
    ]
