# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0002_auto_20171026_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Description',
            field=models.TextField(default=b'', null=True),
        ),
    ]
