# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0003_auto_20170220_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_number',
        ),
        migrations.AddField(
            model_name='show',
            name='tickets_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
