# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0004_auto_20171026_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 15, 27, 27, 759000, tzinfo=utc)),
        ),
    ]
