# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0004_auto_20170429_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
