# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0005_auto_20170222_0944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ticket_type',
            new_name='tickettype',
        ),
    ]
