# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0006_auto_20170222_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='seller',
        ),
    ]
