# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0007_auto_20170222_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='tickapp.tickettype'),
        ),
    ]
