# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0007_auto_20170430_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seller',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
