# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0008_auto_20170501_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, default='0', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
