# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0011_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='tike_type',
            new_name='tike_types',
        ),
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
