# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0013_auto_20170426_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id',
            field=models.CharField(default='0', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
