# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0014_auto_20170426_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='id',
            field=models.AutoField(auto_created=True, default='0', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
