# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0015_auto_20170426_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
